/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lint;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();

        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

}
