/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab6;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    @DisplayName("constructer test")
    public void testConstructer(){

        Resturant classUnderTest = new Resturant("KFC","$$");

        String expectedName = "KFC";
        String expectedCategory = "$$";

        assertEquals(expectedName,classUnderTest.getName());
        assertEquals(expectedCategory,classUnderTest.getPriceCategory());
    }

    @Test
    @DisplayName("toString Method test")
    public void testToString(){
        Resturant classUnderTest = new Resturant("KFC","$$");




        assertEquals("Resturant{name='KFC', priceCategory='$$', raitng'0', review=[]}" , classUnderTest.toString());

    }

    @Test
    @DisplayName("review Method test")
    public void addReviewTest(){

//        Review rev = new Review("good","Qusai",5);
//
//            String expectedBody = "good";
//            String expectedAuthor = "Qusai";
//            int expectedStars = 5;
//        assertEquals(expectedBody , rev.getBody());
//        assertEquals(expectedAuthor , rev.getAuthor());
//        assertEquals(expectedStars , rev.getStarNum());
          Resturant resturant = new Resturant("pizza", "$");

          resturant.addReview("Good","Qusai",3);

          assertEquals("Review{body='Good', author='Qusai', starNum=3}","Review{body='Good', author='Qusai', starNum=3}");

        }
    @Test
    @DisplayName("review Method test")
    public void reviewToString(){

        Review rev = new Review("good","Qusai",5);

        assertEquals("Review{body='good', author='Qusai', starNum=5}",rev.toString());

    }





    }






