/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lint;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static String linter(Path path) {
        int errorLine = 0;
        String errorMsg = "";

        try {
            List<String> lineReader = Files.readAllLines(path);
            for (String line : lineReader) {
                errorLine++;
                if (!(line.isEmpty())) {
                    if (line.contains("if") || line.contains("else") || line.contains(";") || line.contains("}") || line.contains("{")) {

                    } else {
                        System.out.println(" Line " + errorLine + " : Missing semicolon");
                        errorMsg += " Line " + errorLine + " : Missing semicolon.\n";

                    }
                }
            }


        } catch (IOException exception) {
            System.out.println("error happend when reading the file");
        }
        return errorMsg;
    }
}
